import Link from 'next/link';
import { AlertTriangle, ArrowUpRight, CheckCircle2, FileVideo2, Library, Store } from 'lucide-react';
import type { StoreOverview } from './store-admin-data';
const panel = 'rounded-2xl border border-white/[0.07] bg-white/[0.018] p-5';
export default function DashboardClient({ locale, firstName, data }: { locale: string; firstName: string | null; data: StoreOverview }) {
  const base = `/app`;
  const counts = [['Published',data.totals.published],['Drafts',data.totals.drafts],['Archived',data.totals.archived],['Featured',data.totals.featured]] as const;
  return <main className="mx-auto w-full max-w-7xl px-5 py-7 text-white sm:px-8"><header className="mb-7 flex flex-wrap items-end justify-between gap-5"><div><p className="text-[10px] font-semibold uppercase tracking-widest text-blue-300/70">Store Dashboard</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">{firstName ? `Welcome back, ${firstName}.` : 'Your store at a glance.'}</h1><p className="mt-2 text-sm text-white/40">Manage your library and the videos in your collection.</p></div><div className="flex flex-wrap gap-2"><Link href={`${base}/media`} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-white/10 px-4 text-xs text-white/70"><Library size={16}/> Media Library</Link><Link href={`${base}/store/videos`} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-gradient-to-r from-blue-500 to-violet-500 px-4 text-xs font-medium"><Store size={16}/> Videos for Sale</Link></div></header>
  <div className="grid gap-4 sm:grid-cols-2"><section className={panel}><div className="flex items-center justify-between text-xs text-white/45"><h2>Media in Repository</h2><FileVideo2 size={18} className="text-blue-300"/></div><p className="mt-4 text-4xl font-semibold tracking-tight">{data.totals.media.toLocaleString(locale)}</p><p className="mt-2 text-xs text-white/35">All media assets in this workspace.</p></section><section className={panel}><div className="flex items-center justify-between text-xs text-white/45"><h2>Store Videos</h2><Store size={18} className="text-violet-300"/></div><p className="mt-4 text-4xl font-semibold tracking-tight">{data.totals.products.toLocaleString(locale)}</p><p className="mt-2 text-xs text-white/35">{data.totals.live.toLocaleString(locale)} currently visible in the storefront.</p></section></div>
  <section className={`${panel} mt-4`}><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-sm font-medium">Product Overview</h2><Link href={`${base}/store/videos`} className="inline-flex min-h-11 items-center gap-2 text-xs text-violet-300">Manage Videos <ArrowUpRight size={14}/></Link></div><dl className="mt-3 grid grid-cols-2 gap-6 sm:grid-cols-4">{counts.map(([label,value]) => <div key={label}><dt className="text-xs text-white/40">{label}</dt><dd className="mt-2 text-2xl font-medium">{value.toLocaleString(locale)}</dd></div>)}</dl><p className="mt-5 text-[11px] leading-5 text-white/30">Published is the product status. Storefront visibility also requires a publish date that has arrived and an uploaded full video. Featured includes all product statuses.</p></section>
  <div className="mt-4 grid gap-4 lg:grid-cols-[1.4fr_1fr]"><section className={panel}><h2 className="text-sm font-medium">Recent Activity</h2><p className="mt-1 text-xs text-white/35">Latest library uploads and product updates.</p><div className="mt-5 space-y-1">{data.recent.length ? data.recent.map(item => <Link href={`${base}/${item.destination}`} key={item.id} className="flex min-w-0 items-start justify-between gap-4 rounded-lg p-3 hover:bg-white/[0.03]"><div className="min-w-0"><p className="text-xs text-white/75">{item.title}</p><p className="mt-1 truncate text-[11px] text-white/35">{item.detail}</p></div><time dateTime={new Date(item.date).toISOString()} className="shrink-0 text-[10px] text-white/30">{new Date(item.date).toLocaleDateString(locale,{month:'short',day:'numeric'})}</time></Link>) : <p className="py-8 text-center text-xs text-white/35">No uploads or product updates yet.</p>}</div></section><section className={panel}><div className="flex items-center gap-2"><h2 className="text-sm font-medium">System Attention</h2>{data.failureCount ? <AlertTriangle size={17} className="text-amber-300"/> : <CheckCircle2 size={17} className="text-emerald-300"/>}</div><p className="mt-2 text-xs text-white/40">{data.failureCount ? `${data.failureCount} media assets have a failure or recorded error.` : 'No recorded media failures in this workspace.'}</p>{data.failures.map(item => <div key={item.id} className="mt-4 rounded-lg border border-amber-300/10 bg-amber-300/[0.03] p-3"><p className="break-all text-xs text-white/65">{item.name}</p><p className="mt-1 break-all text-[10px] text-amber-200/70">{item.code}</p></div>)}<Link href={`${base}/media`} className="mt-4 inline-flex min-h-11 items-center gap-2 text-xs text-blue-300">Open Media Library <ArrowUpRight size={14}/></Link><p className="mt-2 text-[10px] leading-5 text-white/25">This reflects stored media status, not a live infrastructure health check.</p></section></div>
  <section className={`${panel} mt-4`}><h2 className="text-sm font-medium">Sales, Revenue & Orders</h2><p className="mt-2 text-xs leading-6 text-white/40">Commerce reporting will appear here when payments and orders are available. No sales or revenue data is collected yet.</p><span className="mt-3 inline-block rounded-full border border-white/10 px-3 py-1 text-[10px] text-white/35">Planned</span></section></main>;
}
