import Link from 'next/link';
import { ArrowUpRight, BarChart3 } from 'lucide-react';
import { getAdminContext, getStoreOverview } from '@/src/components/app/store-admin-data';
export const metadata = { title: 'Analytics · HotwifeSonyC' };
export default async function Page({ params }: { params: Promise<{locale:string}> }) {
 const {locale} = await params;
 const context = await getAdminContext(locale);
 if (!context.workspace) return <div className="p-8 text-white/60">No active store workspace is available for this account.</div>;
 const data = await getStoreOverview(context.workspace.id);
 const planned = [['Product Views','Product visits and preview engagement will appear here once tracking is available.'],['Sales Conversion','Conversion reporting depends on future checkout and purchase data.'],['SEO','Search visibility, traffic sources, and indexing reports are planned.'],['Best-Performing Videos','Rankings will use measured views and sales once those signals exist.']];
 return <main className="mx-auto max-w-7xl p-5 sm:p-8"><header><div className="flex items-center gap-2 text-[10px] uppercase tracking-widest text-blue-300"><BarChart3 size={15}/> Store Analytics</div><h1 className="mt-3 text-3xl font-semibold tracking-tight">Understand your store.</h1><p className="mt-2 text-sm text-white/40">Catalog readiness today. Performance insights as measurement becomes available.</p></header><section className="mt-7 rounded-2xl border border-white/[0.07] bg-white/[0.018] p-5"><h2 className="text-sm font-medium">Store Readiness</h2><p className="mt-2 text-xs text-white/35">Current catalog data, not traffic or sales metrics.</p><dl className="mt-6 grid grid-cols-2 gap-6 lg:grid-cols-4">{[['Live Videos',data.totals.live],['Featured Products',data.totals.featured],['Live Videos with Teaser Configured',data.coverage.liveWithTeaser],['Live Videos with Description',data.coverage.liveWithDescription]].map(([label,value]) => <div key={label}><dt className="text-xs leading-5 text-white/40">{label}</dt><dd className="mt-2 text-2xl font-medium">{typeof value === 'number' ? value.toLocaleString(locale) : value}</dd></div>)}</dl><Link href={`/app/store/videos`} className="mt-6 inline-flex min-h-11 items-center gap-2 text-xs text-violet-300">Review Videos for Sale <ArrowUpRight size={14}/></Link></section><section className="mt-4 rounded-2xl border border-white/[0.07] bg-white/[0.018] p-5"><h2 className="text-sm font-medium">Performance Reporting</h2><div className="mt-3 divide-y divide-white/[0.06]">{planned.map(([title,description]) => <div key={title} className="flex items-start justify-between gap-4 py-5"><div><h3 className="text-sm text-white/75">{title}</h3><p className="mt-2 max-w-2xl text-xs leading-6 text-white/35">{description}</p></div><span className="rounded-full border border-white/10 px-3 py-1 text-[9px] text-white/35">Planned</span></div>)}</div></section></main>;
}
