#!/usr/bin/env -S node
import type { Contract as End } from '../../snapshots/25112945bbfce47277c21886bd6142492a366bfcead00d6ac15ec7736511f28f/contract';
import endContract from '../../snapshots/25112945bbfce47277c21886bd6142492a366bfcead00d6ac15ec7736511f28f/contract.json' with { type: 'json' };
import { Migration, MigrationCLI, col, fn, lit, primaryKey } from '@prisma/orm-postgres/migration';

export default class M extends Migration<never, End> {
  override readonly endContractJson = endContract;

  override get operations() {
    return [
      this.createSchema({ schema: 'public' }),
      this.createTable({
        schema: 'public',
        table: 'accountDeletionRequest',
        columns: [
          col('cancelledAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('completedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('requestedAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('userId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'agreement',
        columns: [
          col('agreementDate', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('agreementType', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('auditPdfObjectKey', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('bucketName', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('coPerformerEmail', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('coPerformerLegalName', 'text', {
            notNull: true,
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('completedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('consentVersion', 'text', {
            notNull: true,
            default: lit('1'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('contentDescription', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('fieldSnapshot', 'json', { codecRef: { codecId: 'pg/json@1' } }),
          col('finalDocumentSha256', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('governingLaw', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('jurisdiction', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('performerId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('residentialAddress', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('sentAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('signedPdfObjectKey', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('status', 'text', {
            notNull: true,
            default: lit('DRAFT'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('storageProvider', 'text', {
            notNull: true,
            default: lit('R2'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('templateKey', 'text', {
            notNull: true,
            default: lit('CO_PERFORMER_RELEASE'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('templateVersion', 'text', {
            notNull: true,
            default: lit('MV_CO_MODEL_V12'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('unsignedPdfObjectKey', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('uploaderEmail', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('uploaderLegalName', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('voidedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('workspaceId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'agreementAuditEvent',
        columns: [
          col('agreementId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('eventType', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('ipAddress', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('metadata', 'json', { codecRef: { codecId: 'pg/json@1' } }),
          col('signerId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('userAgent', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('workspaceId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'agreementSigner',
        columns: [
          col('agreementId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('consentAccepted', 'bool', {
            notNull: true,
            default: lit(false),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('consentAcceptedAt', 'timestamptz', {
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('email', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('legalName', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('role', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('signatureMethod', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('signatureObjectKey', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('signatureText', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('signedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('signerIpAddress', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('signerUserAgent', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('signingTokenExpiresAt', 'timestamptz', {
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('signingTokenHash', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('status', 'text', {
            notNull: true,
            default: lit('PENDING'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('viewedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('workspaceId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'auditLog',
        columns: [
          col('action', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('entityId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('entityType', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('ipAddress', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('metadata', 'json', { codecRef: { codecId: 'pg/json@1' } }),
          col('userAgent', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('userId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'creator',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('displayName', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('legalName', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('ownerUserId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('status', 'text', {
            notNull: true,
            default: lit('ACTIVE'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('workspaceId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'distributionJob',
        columns: [
          col('completedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('creatorId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('defaultCaption', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('lastErrorCode', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('lastErrorMessage', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('mediaAssetId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('publishMode', 'text', {
            notNull: true,
            default: lit('NOW'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('scheduledAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('startedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('status', 'text', {
            notNull: true,
            default: lit('DRAFT'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('workspaceId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'emailVerificationToken',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('expiresAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('tokenHash', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('usedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('userId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'loginAttempt',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('email', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('ipAddress', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('successful', 'bool', {
            notNull: true,
            default: lit(false),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('userAgent', 'text', { codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'mediaAsset',
        columns: [
          col('bucketName', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('contentType', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('creatorId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('durationSeconds', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('fileSize', 'int8', { notNull: true, codecRef: { codecId: 'pg/int8@1' } }),
          col('folderId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('height', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('lastErrorCode', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('lastErrorMessage', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('mediaType', 'text', {
            notNull: true,
            default: lit('VIDEO'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('objectEtag', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('objectKey', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('originalFileName', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('processingCompletedAt', 'timestamptz', {
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('processingStartedAt', 'timestamptz', {
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('status', 'text', {
            notNull: true,
            default: lit('UPLOADING'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('storageProvider', 'text', {
            notNull: true,
            default: lit('R2'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('thumbnailObjectKey', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('uploadCompletedAt', 'timestamptz', {
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('width', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('workspaceId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'mediaAssetCategory',
        columns: [
          col('categoryId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('mediaAssetId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['mediaAssetId', 'categoryId'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'mediaAssetPerformer',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('mediaAssetId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('performerId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('workspaceId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['mediaAssetId', 'performerId'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'mediaCategory',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('normalizedName', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('workspaceId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'passwordResetToken',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('expiresAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('tokenHash', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('usedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('userId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'performer',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('dateOfBirth', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('displayName', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('email', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('legalName', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('notes', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('phone', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('status', 'text', {
            notNull: true,
            default: lit('ACTIVE'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('workspaceId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'performerDocument',
        columns: [
          col('bucketName', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('contentType', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('documentNumber', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('documentType', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('expiresAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('fileSize', 'int8', { notNull: true, codecRef: { codecId: 'pg/int8@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('issuedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('notes', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('objectKey', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('performerId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('status', 'text', {
            notNull: true,
            default: lit('ACTIVE'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('storageProvider', 'text', {
            notNull: true,
            default: lit('R2'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('title', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('workspaceId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'performerLibraryFolder',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('folderType', 'text', {
            notNull: true,
            default: lit('CUSTOM'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('isRequired', 'bool', {
            notNull: true,
            default: lit(false),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('isSystem', 'bool', {
            notNull: true,
            default: lit(false),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('normalizedName', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('parentId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('performerId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('sortOrder', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('status', 'text', {
            notNull: true,
            default: lit('ACTIVE'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('systemKey', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('workspaceId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'platformAccount',
        columns: [
          col('accessTokenEncrypted', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('connectionType', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('creatorId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('externalAccountId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('externalDisplayName', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('externalUsername', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('lastErrorCode', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('lastErrorMessage', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('lastSyncAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('lastVerifiedAt', 'timestamptz', {
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('platform', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('refreshTokenEncrypted', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('status', 'text', {
            notNull: true,
            default: lit('DISCONNECTED'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('tokenExpiresAt', 'timestamptz', {
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('workspaceId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'platformPublication',
        columns: [
          col('attemptCount', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('caption', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('creatorId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('distributionJobId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('externalPostId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('externalPostUrl', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('failedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('lastErrorCode', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('lastErrorMessage', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('platform', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('platformAccountId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('publishedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('scheduledAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('startedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('status', 'text', {
            notNull: true,
            default: lit('PENDING'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('workspaceId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'recoveryCode',
        columns: [
          col('codeHash', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('used', 'bool', {
            notNull: true,
            default: lit(false),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('usedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('userId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'session',
        columns: [
          col('clientType', 'text', {
            notNull: true,
            default: lit('WEB'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('expiresAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('ipAddress', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('lastSeenAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('revokedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('status', 'text', {
            notNull: true,
            default: lit('ACTIVE'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('tokenHash', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('userAgent', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('userId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'twoFactorMethod',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('enabled', 'bool', {
            notNull: true,
            default: lit(false),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('secret', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('userId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('verifiedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'user',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('email', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('emailVerifiedAt', 'timestamptz', {
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('firstName', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('lastName', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('locale', 'text', {
            notNull: true,
            default: lit('en-US'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('passwordHash', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('status', 'text', {
            notNull: true,
            default: lit('PENDING'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('timezone', 'text', {
            notNull: true,
            default: lit('UTC'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'workspace',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('onboardingCompletedAt', 'timestamptz', {
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('onboardingStatus', 'text', {
            notNull: true,
            default: lit('WELCOME'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('status', 'text', {
            notNull: true,
            default: lit('ACTIVE'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('type', 'text', {
            notNull: true,
            default: lit('CREATOR'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'workspaceMember',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('role', 'text', {
            notNull: true,
            default: lit('OPERATOR'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('userId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('workspaceId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.addUnique({
        schema: 'public',
        table: 'agreement',
        constraint: 'agreement_unsignedPdfObjectKey_key',
        columns: ['unsignedPdfObjectKey'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'agreement',
        constraint: 'agreement_signedPdfObjectKey_key',
        columns: ['signedPdfObjectKey'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'agreement',
        constraint: 'agreement_auditPdfObjectKey_key',
        columns: ['auditPdfObjectKey'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'agreementSigner',
        constraint: 'agreementSigner_signingTokenHash_key',
        columns: ['signingTokenHash'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'agreementSigner',
        constraint: 'agreementSigner_signatureObjectKey_key',
        columns: ['signatureObjectKey'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'agreementSigner',
        constraint: 'agreementSigner_agreementId_role_key',
        columns: ['agreementId', 'role'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'emailVerificationToken',
        constraint: 'emailVerificationToken_tokenHash_key',
        columns: ['tokenHash'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'mediaAsset',
        constraint: 'mediaAsset_objectKey_key',
        columns: ['objectKey'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'mediaCategory',
        constraint: 'mediaCategory_workspaceId_normalizedName_key',
        columns: ['workspaceId', 'normalizedName'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'passwordResetToken',
        constraint: 'passwordResetToken_tokenHash_key',
        columns: ['tokenHash'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'performerDocument',
        constraint: 'performerDocument_objectKey_key',
        columns: ['objectKey'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'performerLibraryFolder',
        constraint: 'performerLibraryFolder_performerId_parentId_normalizedName_key',
        columns: ['performerId', 'parentId', 'normalizedName'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'performerLibraryFolder',
        constraint: 'performerLibraryFolder_performerId_systemKey_key',
        columns: ['performerId', 'systemKey'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'platformAccount',
        constraint: 'platformAccount_creatorId_platform_externalAccountId_key',
        columns: ['creatorId', 'platform', 'externalAccountId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'platformPublication',
        constraint: 'platformPublication_distributionJobId_platformAccountId_key',
        columns: ['distributionJobId', 'platformAccountId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'session',
        constraint: 'session_tokenHash_key',
        columns: ['tokenHash'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'twoFactorMethod',
        constraint: 'twoFactorMethod_userId_key',
        columns: ['userId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'user',
        constraint: 'user_email_key',
        columns: ['email'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'workspaceMember',
        constraint: 'workspaceMember_workspaceId_userId_key',
        columns: ['workspaceId', 'userId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'accountDeletionRequest',
        index: 'accountDeletionRequest_userId_idx_a489d58a',
        columns: ['userId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'agreement',
        index: 'agreement_createdAt_idx_9575dbd7',
        columns: ['createdAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'agreement',
        index: 'agreement_performerId_idx_568c0ad9',
        columns: ['performerId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'agreement',
        index: 'agreement_status_idx_e98638ab',
        columns: ['status'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'agreement',
        index: 'agreement_templateKey_idx_baa83fc2',
        columns: ['templateKey'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'agreement',
        index: 'agreement_workspaceId_idx_ba65f874',
        columns: ['workspaceId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'agreementAuditEvent',
        index: 'agreementAuditEvent_agreementId_idx_ab6426ca',
        columns: ['agreementId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'agreementAuditEvent',
        index: 'agreementAuditEvent_createdAt_idx_9575dbd7',
        columns: ['createdAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'agreementAuditEvent',
        index: 'agreementAuditEvent_eventType_idx_e4cf7742',
        columns: ['eventType'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'agreementAuditEvent',
        index: 'agreementAuditEvent_signerId_idx_869496e8',
        columns: ['signerId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'agreementAuditEvent',
        index: 'agreementAuditEvent_workspaceId_idx_ba65f874',
        columns: ['workspaceId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'agreementSigner',
        index: 'agreementSigner_agreementId_idx_ab6426ca',
        columns: ['agreementId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'agreementSigner',
        index: 'agreementSigner_createdAt_idx_9575dbd7',
        columns: ['createdAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'agreementSigner',
        index: 'agreementSigner_signingTokenExpiresAt_idx_d176429a',
        columns: ['signingTokenExpiresAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'agreementSigner',
        index: 'agreementSigner_status_idx_e98638ab',
        columns: ['status'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'agreementSigner',
        index: 'agreementSigner_workspaceId_idx_ba65f874',
        columns: ['workspaceId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'auditLog',
        index: 'auditLog_createdAt_idx_9575dbd7',
        columns: ['createdAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'auditLog',
        index: 'auditLog_entityType_entityId_idx_ea0fa809',
        columns: ['entityType', 'entityId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'auditLog',
        index: 'auditLog_userId_idx_a489d58a',
        columns: ['userId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'creator',
        index: 'creator_ownerUserId_idx_f93ae154',
        columns: ['ownerUserId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'creator',
        index: 'creator_workspaceId_idx_ba65f874',
        columns: ['workspaceId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'distributionJob',
        index: 'distributionJob_createdAt_idx_9575dbd7',
        columns: ['createdAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'distributionJob',
        index: 'distributionJob_creatorId_idx_3a77d800',
        columns: ['creatorId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'distributionJob',
        index: 'distributionJob_mediaAssetId_idx_523c8890',
        columns: ['mediaAssetId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'distributionJob',
        index: 'distributionJob_scheduledAt_idx_f69c1204',
        columns: ['scheduledAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'distributionJob',
        index: 'distributionJob_status_idx_e98638ab',
        columns: ['status'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'distributionJob',
        index: 'distributionJob_workspaceId_idx_ba65f874',
        columns: ['workspaceId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'emailVerificationToken',
        index: 'emailVerificationToken_expiresAt_idx_6b6b8c10',
        columns: ['expiresAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'emailVerificationToken',
        index: 'emailVerificationToken_userId_idx_a489d58a',
        columns: ['userId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'loginAttempt',
        index: 'loginAttempt_createdAt_idx_9575dbd7',
        columns: ['createdAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'loginAttempt',
        index: 'loginAttempt_email_idx_46df9cad',
        columns: ['email'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'loginAttempt',
        index: 'loginAttempt_ipAddress_idx_632dc32c',
        columns: ['ipAddress'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'mediaAsset',
        index: 'mediaAsset_createdAt_idx_9575dbd7',
        columns: ['createdAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'mediaAsset',
        index: 'mediaAsset_creatorId_idx_3a77d800',
        columns: ['creatorId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'mediaAsset',
        index: 'mediaAsset_folderId_idx_5985e562',
        columns: ['folderId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'mediaAsset',
        index: 'mediaAsset_mediaType_idx_c1745d97',
        columns: ['mediaType'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'mediaAsset',
        index: 'mediaAsset_status_idx_e98638ab',
        columns: ['status'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'mediaAsset',
        index: 'mediaAsset_workspaceId_idx_ba65f874',
        columns: ['workspaceId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'mediaAssetCategory',
        index: 'mediaAssetCategory_categoryId_idx_15c304f2',
        columns: ['categoryId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'mediaAssetCategory',
        index: 'mediaAssetCategory_createdAt_idx_9575dbd7',
        columns: ['createdAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'mediaAssetCategory',
        index: 'mediaAssetCategory_mediaAssetId_idx_523c8890',
        columns: ['mediaAssetId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'mediaAssetPerformer',
        index: 'mediaAssetPerformer_createdAt_idx_9575dbd7',
        columns: ['createdAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'mediaAssetPerformer',
        index: 'mediaAssetPerformer_mediaAssetId_idx_523c8890',
        columns: ['mediaAssetId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'mediaAssetPerformer',
        index: 'mediaAssetPerformer_performerId_idx_568c0ad9',
        columns: ['performerId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'mediaAssetPerformer',
        index: 'mediaAssetPerformer_workspaceId_idx_ba65f874',
        columns: ['workspaceId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'mediaCategory',
        index: 'mediaCategory_createdAt_idx_9575dbd7',
        columns: ['createdAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'mediaCategory',
        index: 'mediaCategory_name_idx_ce87e6ba',
        columns: ['name'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'mediaCategory',
        index: 'mediaCategory_workspaceId_idx_ba65f874',
        columns: ['workspaceId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'passwordResetToken',
        index: 'passwordResetToken_expiresAt_idx_6b6b8c10',
        columns: ['expiresAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'passwordResetToken',
        index: 'passwordResetToken_userId_idx_a489d58a',
        columns: ['userId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'performer',
        index: 'performer_createdAt_idx_9575dbd7',
        columns: ['createdAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'performer',
        index: 'performer_displayName_idx_6daae81f',
        columns: ['displayName'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'performer',
        index: 'performer_status_idx_e98638ab',
        columns: ['status'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'performer',
        index: 'performer_workspaceId_idx_ba65f874',
        columns: ['workspaceId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'performerDocument',
        index: 'performerDocument_createdAt_idx_9575dbd7',
        columns: ['createdAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'performerDocument',
        index: 'performerDocument_documentType_idx_e4b68595',
        columns: ['documentType'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'performerDocument',
        index: 'performerDocument_expiresAt_idx_6b6b8c10',
        columns: ['expiresAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'performerDocument',
        index: 'performerDocument_performerId_idx_568c0ad9',
        columns: ['performerId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'performerDocument',
        index: 'performerDocument_status_idx_e98638ab',
        columns: ['status'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'performerDocument',
        index: 'performerDocument_workspaceId_idx_ba65f874',
        columns: ['workspaceId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'performerLibraryFolder',
        index: 'performerLibraryFolder_createdAt_idx_9575dbd7',
        columns: ['createdAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'performerLibraryFolder',
        index: 'performerLibraryFolder_folderType_idx_986d5afc',
        columns: ['folderType'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'performerLibraryFolder',
        index: 'performerLibraryFolder_isRequired_idx_9a337f8c',
        columns: ['isRequired'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'performerLibraryFolder',
        index: 'performerLibraryFolder_isSystem_idx_a4a7992e',
        columns: ['isSystem'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'performerLibraryFolder',
        index: 'performerLibraryFolder_parentId_idx_6a68f597',
        columns: ['parentId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'performerLibraryFolder',
        index: 'performerLibraryFolder_performerId_idx_568c0ad9',
        columns: ['performerId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'performerLibraryFolder',
        index: 'performerLibraryFolder_sortOrder_idx_ebf2eac2',
        columns: ['sortOrder'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'performerLibraryFolder',
        index: 'performerLibraryFolder_status_idx_e98638ab',
        columns: ['status'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'performerLibraryFolder',
        index: 'performerLibraryFolder_workspaceId_idx_ba65f874',
        columns: ['workspaceId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'platformAccount',
        index: 'platformAccount_creatorId_idx_3a77d800',
        columns: ['creatorId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'platformAccount',
        index: 'platformAccount_platform_idx_b8f7b2d3',
        columns: ['platform'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'platformAccount',
        index: 'platformAccount_status_idx_e98638ab',
        columns: ['status'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'platformAccount',
        index: 'platformAccount_workspaceId_idx_ba65f874',
        columns: ['workspaceId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'platformPublication',
        index: 'platformPublication_creatorId_idx_3a77d800',
        columns: ['creatorId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'platformPublication',
        index: 'platformPublication_distributionJobId_idx_99f254cf',
        columns: ['distributionJobId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'platformPublication',
        index: 'platformPublication_platformAccountId_idx_aa859782',
        columns: ['platformAccountId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'platformPublication',
        index: 'platformPublication_platform_idx_b8f7b2d3',
        columns: ['platform'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'platformPublication',
        index: 'platformPublication_scheduledAt_idx_f69c1204',
        columns: ['scheduledAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'platformPublication',
        index: 'platformPublication_status_idx_e98638ab',
        columns: ['status'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'platformPublication',
        index: 'platformPublication_workspaceId_idx_ba65f874',
        columns: ['workspaceId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'recoveryCode',
        index: 'recoveryCode_userId_idx_a489d58a',
        columns: ['userId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'session',
        index: 'session_expiresAt_idx_6b6b8c10',
        columns: ['expiresAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'session',
        index: 'session_userId_idx_a489d58a',
        columns: ['userId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'workspaceMember',
        index: 'workspaceMember_userId_idx_a489d58a',
        columns: ['userId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'workspaceMember',
        index: 'workspaceMember_workspaceId_idx_ba65f874',
        columns: ['workspaceId'],
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'accountDeletionRequest',
        foreignKey: {
          name: 'accountDeletionRequest_userId_fkey',
          columns: ['userId'],
          references: { schema: 'public', table: 'user', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'agreement',
        foreignKey: {
          name: 'agreement_workspaceId_fkey',
          columns: ['workspaceId'],
          references: { schema: 'public', table: 'workspace', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'agreement',
        foreignKey: {
          name: 'agreement_performerId_fkey',
          columns: ['performerId'],
          references: { schema: 'public', table: 'performer', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'agreementAuditEvent',
        foreignKey: {
          name: 'agreementAuditEvent_workspaceId_fkey',
          columns: ['workspaceId'],
          references: { schema: 'public', table: 'workspace', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'agreementAuditEvent',
        foreignKey: {
          name: 'agreementAuditEvent_agreementId_fkey',
          columns: ['agreementId'],
          references: { schema: 'public', table: 'agreement', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'agreementAuditEvent',
        foreignKey: {
          name: 'agreementAuditEvent_signerId_fkey',
          columns: ['signerId'],
          references: { schema: 'public', table: 'agreementSigner', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'agreementSigner',
        foreignKey: {
          name: 'agreementSigner_workspaceId_fkey',
          columns: ['workspaceId'],
          references: { schema: 'public', table: 'workspace', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'agreementSigner',
        foreignKey: {
          name: 'agreementSigner_agreementId_fkey',
          columns: ['agreementId'],
          references: { schema: 'public', table: 'agreement', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'auditLog',
        foreignKey: {
          name: 'auditLog_userId_fkey',
          columns: ['userId'],
          references: { schema: 'public', table: 'user', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'creator',
        foreignKey: {
          name: 'creator_workspaceId_fkey',
          columns: ['workspaceId'],
          references: { schema: 'public', table: 'workspace', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'creator',
        foreignKey: {
          name: 'creator_ownerUserId_fkey',
          columns: ['ownerUserId'],
          references: { schema: 'public', table: 'user', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'distributionJob',
        foreignKey: {
          name: 'distributionJob_workspaceId_fkey',
          columns: ['workspaceId'],
          references: { schema: 'public', table: 'workspace', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'distributionJob',
        foreignKey: {
          name: 'distributionJob_creatorId_fkey',
          columns: ['creatorId'],
          references: { schema: 'public', table: 'creator', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'distributionJob',
        foreignKey: {
          name: 'distributionJob_mediaAssetId_fkey',
          columns: ['mediaAssetId'],
          references: { schema: 'public', table: 'mediaAsset', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'emailVerificationToken',
        foreignKey: {
          name: 'emailVerificationToken_userId_fkey',
          columns: ['userId'],
          references: { schema: 'public', table: 'user', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'mediaAsset',
        foreignKey: {
          name: 'mediaAsset_workspaceId_fkey',
          columns: ['workspaceId'],
          references: { schema: 'public', table: 'workspace', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'mediaAsset',
        foreignKey: {
          name: 'mediaAsset_creatorId_fkey',
          columns: ['creatorId'],
          references: { schema: 'public', table: 'creator', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'mediaAsset',
        foreignKey: {
          name: 'mediaAsset_folderId_fkey',
          columns: ['folderId'],
          references: { schema: 'public', table: 'performerLibraryFolder', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'mediaAssetCategory',
        foreignKey: {
          name: 'mediaAssetCategory_mediaAssetId_fkey',
          columns: ['mediaAssetId'],
          references: { schema: 'public', table: 'mediaAsset', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'mediaAssetCategory',
        foreignKey: {
          name: 'mediaAssetCategory_categoryId_fkey',
          columns: ['categoryId'],
          references: { schema: 'public', table: 'mediaCategory', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'mediaAssetPerformer',
        foreignKey: {
          name: 'mediaAssetPerformer_workspaceId_fkey',
          columns: ['workspaceId'],
          references: { schema: 'public', table: 'workspace', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'mediaAssetPerformer',
        foreignKey: {
          name: 'mediaAssetPerformer_mediaAssetId_fkey',
          columns: ['mediaAssetId'],
          references: { schema: 'public', table: 'mediaAsset', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'mediaAssetPerformer',
        foreignKey: {
          name: 'mediaAssetPerformer_performerId_fkey',
          columns: ['performerId'],
          references: { schema: 'public', table: 'performer', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'mediaCategory',
        foreignKey: {
          name: 'mediaCategory_workspaceId_fkey',
          columns: ['workspaceId'],
          references: { schema: 'public', table: 'workspace', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'passwordResetToken',
        foreignKey: {
          name: 'passwordResetToken_userId_fkey',
          columns: ['userId'],
          references: { schema: 'public', table: 'user', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'performer',
        foreignKey: {
          name: 'performer_workspaceId_fkey',
          columns: ['workspaceId'],
          references: { schema: 'public', table: 'workspace', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'performerDocument',
        foreignKey: {
          name: 'performerDocument_workspaceId_fkey',
          columns: ['workspaceId'],
          references: { schema: 'public', table: 'workspace', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'performerDocument',
        foreignKey: {
          name: 'performerDocument_performerId_fkey',
          columns: ['performerId'],
          references: { schema: 'public', table: 'performer', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'performerLibraryFolder',
        foreignKey: {
          name: 'performerLibraryFolder_workspaceId_fkey',
          columns: ['workspaceId'],
          references: { schema: 'public', table: 'workspace', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'performerLibraryFolder',
        foreignKey: {
          name: 'performerLibraryFolder_performerId_fkey',
          columns: ['performerId'],
          references: { schema: 'public', table: 'performer', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'performerLibraryFolder',
        foreignKey: {
          name: 'performerLibraryFolder_parentId_fkey',
          columns: ['parentId'],
          references: { schema: 'public', table: 'performerLibraryFolder', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'platformAccount',
        foreignKey: {
          name: 'platformAccount_workspaceId_fkey',
          columns: ['workspaceId'],
          references: { schema: 'public', table: 'workspace', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'platformAccount',
        foreignKey: {
          name: 'platformAccount_creatorId_fkey',
          columns: ['creatorId'],
          references: { schema: 'public', table: 'creator', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'platformPublication',
        foreignKey: {
          name: 'platformPublication_workspaceId_fkey',
          columns: ['workspaceId'],
          references: { schema: 'public', table: 'workspace', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'platformPublication',
        foreignKey: {
          name: 'platformPublication_creatorId_fkey',
          columns: ['creatorId'],
          references: { schema: 'public', table: 'creator', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'platformPublication',
        foreignKey: {
          name: 'platformPublication_distributionJobId_fkey',
          columns: ['distributionJobId'],
          references: { schema: 'public', table: 'distributionJob', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'platformPublication',
        foreignKey: {
          name: 'platformPublication_platformAccountId_fkey',
          columns: ['platformAccountId'],
          references: { schema: 'public', table: 'platformAccount', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'recoveryCode',
        foreignKey: {
          name: 'recoveryCode_userId_fkey',
          columns: ['userId'],
          references: { schema: 'public', table: 'user', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'session',
        foreignKey: {
          name: 'session_userId_fkey',
          columns: ['userId'],
          references: { schema: 'public', table: 'user', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'twoFactorMethod',
        foreignKey: {
          name: 'twoFactorMethod_userId_fkey',
          columns: ['userId'],
          references: { schema: 'public', table: 'user', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'workspaceMember',
        foreignKey: {
          name: 'workspaceMember_workspaceId_fkey',
          columns: ['workspaceId'],
          references: { schema: 'public', table: 'workspace', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'workspaceMember',
        foreignKey: {
          name: 'workspaceMember_userId_fkey',
          columns: ['userId'],
          references: { schema: 'public', table: 'user', columns: ['id'] },
        },
      }),
    ];
  }
}

MigrationCLI.run(import.meta.url, M);
